name: Build EndStone-PlayerRegister Plugin

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build clang libc++-dev

    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build plugin
      run: |
        cmake --build build --config Release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: endstone-player-register-plugin
        path: |
          build/*.so
          build/*.dll
          build/*.dylib

    - name: Check build results
      run: |
        ls -la build/
        echo "Build completed successfully!"