name: Build EndStone-PlayerRegister Plugin

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release, Debug]
        exclude:
          - os: windows-latest
            build_type: Debug

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build clang libc++-dev

    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install cmake ninja

    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: |
        cmake --build build --config ${{ matrix.build_type }}

    - name: Test (if tests exist)
      run: |
        cd build
        ctest --output-on-failure
      continue-on-error: true

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: endstone-player-register-${{ matrix.os }}-${{ matrix.build_type }}
        path: |
          build/*.dll
          build/*.so
          build/*.dylib